/* This file should be autogenerated based on conventions */
import { css, unsafeCSS } from "lit-element";
import { injectGlobalCss } from "./util";

// @ts-ignore
import { registerStyles } from "@vaadin/vaadin-themable-mixin/register-styles";

// Include design-system-name/global/**/*.css
// @ts-ignore
import globalCss from "./global/global.css";
injectGlobalCss(globalCss);

// Include design-system-name/component-styles/[component-name]/*.css and map to component-name
// @ts-ignore
import textfieldCss1 from "./component-styles/vaadin-text-field/textfield-styles.css";
registerStyles(
  "vaadin-text-field",
  css`
    ${unsafeCSS(textfieldCss1)}
  `
);
import textfieldCss2 from "./component-styles/vaadin-text-field/blue-border.css";
registerStyles(
  "vaadin-text-field",
  css`
    ${unsafeCSS(textfieldCss2)}
  `
);

import buttonCss1 from "./component-styles/vaadin-button/default-button.css";
registerStyles(
  "vaadin-button",
  css`
    ${unsafeCSS(buttonCss1)}
  `
);
import mybuttonCss1 from "./component-styles/my-button/my-button.css";
registerStyles(
  "my-button",
  css`
    ${unsafeCSS(mybuttonCss1)}
  `
);
